### ISSUE TITLE
[Componentes] Card (dashboard)

### ISSUE THREAD

**Issue by JuAintablian** [ng-devs/controle-estoque-front#4]
![image](https://user-images.githubusercontent.com/26873436/136833094-b2bb6596-6ac5-44fb-a8d8-ed10801ec2b3.png)

**Comment by dev-cristhian** [comment]
Componente criado conforme solicitado.

![image](https://user-images.githubusercontent.com/70783719/137058959-42987832-6610-4c5e-85f4-381e81dd6946.png)

A paleta de cores escolhida é referente ao tema Indigo & Pink, tema escolhido pelo time na criação do projeto
