### ISSUE TITLE
[Geral] Definição de padrão de projeto

### ISSUE THREAD

**Issue by JuAintablian** [ng-devs/controle-estoque-front#7]
- Estrutura de pastas

**Comment by dev-cristhian** [comment]
Boa noite pessoal,

Conforme conversamos na nossa última reunião, o padrão de nomenclatura dos componentes será mesmo o kebab-case?
De acordo com o style guide do Angular (https://angular.io/guide/styleguide) essa seria a forma correta de nomear os seletores de componentes.

Além disso, para a organização dos componentes sugiro a criação de um diretório, assim como na imagem em anexo.

Ainda, sugiro para o padrão de estruturas de pasta darem um lida nesse artigo, (https://medium.com/@alexandrebeato/pt-br-arquitetura-para-projeto-em-angular-com-f%C3%A1cil-desenvolvimento-e-manuten%C3%A7%C3%A3o-817a15e0d10c) pois é uma idéia que embasa a sugestão acima.

Fico no aguado dos demais para definição dos padrões.


![image2](https://user-images.githubusercontent.com/70783719/136873149-137561c7-ae8c-42cf-a800-50dc5155ea64.png)
![image](https://user-images.githubusercontent.com/70783719/136873152-030a0efd-76e7-454b-9999-968707086842.png)

**Comment by dev-cristhian** [comment]
Pessoal, boa noite!

O João Vitor criou um grupo no WhatsApp para podermos definir os detalhes do projeto (https://chat.whatsapp.com/Ex3nmk4CGan8c725Yu8yqs).

Contudo, apenas nos dois nos posicionamos, sendo assim, após conversarmos definimos o tipo de estrutura e padrão que inicialmente o projeto deve seguir, segue os detalhes:

✅ - Estrutura e pastas: A base é a do artigo citada no comentário anterior, contudo, a forma que utilizaremos é igual a da imagem abaixo.

![image](https://user-images.githubusercontent.com/70783719/137047362-aa5a7ba1-2252-4e53-b37d-681ce5fdf105.png)


✅ - Nomenclatura para componentes e nomes de classes css: **kebab-case**
✅ - Nomenclatura para commit: **lower case** para a mensagem e para palavras compostas **kebab-case**
✅ - Padrão dos commit: **atomic commits.**, **conventional commits.**
✅ - Arquivo com o padrão dos conventional commits com os emojis para adicionar ao vs code: https://1drv.ms/t/s!Av5ge70-Tzq5iJg3bDzudxb6KfQXvA?e=jkJQPz
✅ - Padrão para nome da branch: branch de desenvolvimento/nº da issue-nome-da-tarefa-principal (Ex: develop/feature/10-create-input-component)
✅ - Extensão utilizada para facilitar e padronizar os commits: Commit Message Editor (https://marketplace.visualstudio.com/items?itemName=adam-bender.commit-message-editor)
✅ - Para todos os itens mencionados acima, utilizar o inglês.


Como os demais integrantes não responderam a mensagem do João Vitor, definimos esses padrões, contudo, é importante pontuar que, estamos abertos para sugestões e melhorias.
